clear DATA

DATA.SYSMON.DATA=MATB_DATA.SYSMON.DATA;
DATA.TRACK.DATA=MATB_DATA.TRACK.DATA;
DATA.COMM=MATB_DATA.COMM;
DATA.RESMAN.DATA=MATB_DATA.RESMAN.DATA;

DATA.TRACK.Difficulty=MATB_DATA.TRACK.Difficulty;
DATA.RESMAN.FluxPompe=MATB_DATA.RESMAN.FluxPompe;

DATA.ScenarioType=MATB_DATA.ScenarioType;
DATA.ScenarioDuration=MATB_DATA.ScenarioDuration;

DATA.EVENT=MATB_DATA.EVENT;

dt=char(datetime); dt([3 7 12 15 18])='_';
save(['DATA/DATA_' dt '.mat'],'DATA');