function slidervalues
% Creer un questionnaire de type NASA-TLX et récupère les réponses des
% participants dans le fichier RepQuestionnaire.mat --------------ALEX

Answers = [];
Questionnaire = uifigure('Position',[428 32 1100 1020]); 

instruc1 = uilabel(Questionnaire,...
    'Position',[245 970 662 30],...
    'Text','Veuillez à présent compléter ce questionnaire en indiquant pour chaque item', 'Fontsize', 18);
instruc2 = uilabel(Questionnaire,...
    'Position',[372 930 662 30],...
    'Text','quel à été votre ressenti au cours de la tâche', 'Fontsize', 18);


label1 = uilabel(Questionnaire,...
    'Position',[220 870 662 30],... 
    'Text','EXIGENCE MENTALE: Quel degré d`activité mentale était exigé pour réaliser cette tâche?', 'Fontsize', 14);
min1 = uilabel(Questionnaire,...
    'Position',[192 795 662 30],...
    'Text','Très faible', 'Fontsize', 12);
max1 = uilabel(Questionnaire,...
    'Position',[855 795 662 30],...
    'Text','Très élevé', 'Fontsize', 12);
sld1 = uislider(Questionnaire,...
    'Position',[220 850 662 15],... 
    'MajorTicks',[0 25 50 75 100],...
    'MinorTicks',[],...
    'ValueChangedFcn',@(sld1,event) StoreValue1(sld1));

label2 = uilabel(Questionnaire,...
    'Position',[220 730 662 30],...
    'Text','EXIGENCE PHYSIQUE: Quel degré d`activité physique était exigé pour réaliser cette tâche?', 'Fontsize', 14);
min2 = uilabel(Questionnaire,...
    'Position',[192 655 662 30],...
    'Text','Très faible', 'Fontsize', 12);
max2 = uilabel(Questionnaire,...
    'Position',[855 655 662 30],...
    'Text','Très élevé', 'Fontsize', 12);
sld2 = uislider(Questionnaire,...
    'Position',[220 710 662 15],...
    'MajorTicks',[0 25 50 75 100],...
    'MinorTicks',[],...
    'ValueChangedFcn',@(sld2,event) StoreValue2(sld2));

label3 = uilabel(Questionnaire,...
    'Position',[220 590 662 30],...
    'Text','EXIGENCE TEMPORELLE: Quel degré de pression temporelle avez-vous ressenti lors de cette tâche?', 'Fontsize', 14);
min3 = uilabel(Questionnaire,...
    'Position',[192 515 662 30],...
    'Text','Très faible', 'Fontsize', 12);
max3 = uilabel(Questionnaire,...
    'Position',[855 515 662 30],...
    'Text','Très élevé', 'Fontsize', 12);
sld3 = uislider(Questionnaire,...
    'Position',[220 570 662 15],...
    'MajorTicks',[0 25 50 75 100],...
    'MinorTicks',[],...
    'ValueChangedFcn',@(sld3,event) StoreValue3(sld3));

label4 = uilabel(Questionnaire,...
    'Position',[220 450 662 30],...
    'Text','PERFORMANCE: Avec quel succès pensez-vous avoir réalisé cette tâche?', 'Fontsize', 14);
min4 = uilabel(Questionnaire,...
    'Position',[192 375 662 30],...
    'Text','Très faible', 'Fontsize', 12);
max4 = uilabel(Questionnaire,...
    'Position',[855 375 662 30],...
    'Text','Très élevé', 'Fontsize', 12);
sld4 = uislider(Questionnaire,...
    'Position',[220 430 662 15],...
    'MajorTicks',[0 25 50 75 100],...
    'MinorTicks',[],...
    'ValueChangedFcn',@(sld4,event) StoreValue4(sld4));

label5 = uilabel(Questionnaire,...
    'Position',[220 310 662 30],...
    'Text','EFFORT: Quel niveau d`effort avez-vous fourni pour réaliser cette tâche?', 'Fontsize', 14);
min5 = uilabel(Questionnaire,...
    'Position',[192 235 662 30],...
    'Text','Très faible', 'Fontsize', 12);
max5 = uilabel(Questionnaire,...
    'Position',[855 235 662 30],...
    'Text','Très élevé', 'Fontsize', 12);
sld5 = uislider(Questionnaire,...
    'Position',[220 290 662 15],...
    'MajorTicks',[0 25 50 75 100],...
    'MinorTicks',[],...
    'ValueChangedFcn',@(sld5,event) StoreValue5(sld5));

label6 = uilabel(Questionnaire,...
    'Position',[220 170 662 30],...
    'Text','FRUSTRATION: Avez-vous ressenti du découragement, de l`irritation ou du stress lors de cette tâche?','Fontsize', 14);
min6 = uilabel(Questionnaire,...
    'Position',[192 95 662 30],...
    'Text','Très faible', 'Fontsize', 12);
max6 = uilabel(Questionnaire,...
    'Position',[855 95 662 30],...
    'Text','Très élevé', 'Fontsize', 12);
sld6 = uislider(Questionnaire,...
    'Position',[220 150 662 15],...
    'MajorTicks',[0 25 50 75 100],...
    'MinorTicks',[],...
    'ValueChangedFcn',@(sld6,event) StoreValue6(sld6));

butt = uibutton(Questionnaire,...
    'Position', [500 40 100 30],...
    'Text', 'TERMINE !!', 'Fontsize', 16, 'ButtonPushedFcn', @(butt, event) PushB(butt));

% Create ValueChangedFcn callbacks

function StoreValue1(sld1)
Answers(1,1) = sld1.Value;
end

function StoreValue2(sld2)
Answers(2,1) = sld2.Value;
end

function StoreValue3(sld3)
Answers(3,1) = sld3.Value;
end

function StoreValue4(sld4)
Answers(4,1) = sld4.Value;
end

function StoreValue5(sld5)
Answers(5,1) = sld5.Value;
end

function StoreValue6(sld6)
Answers(6,1) = sld6.Value;
end


% Create push button callbacks

function PushB(butt)
path = ['D:\a.lafont\Post-doc\COCPIT\MATB\MATB_COCPIT\DATA'];
filename = ['RepQuestionnaire-',datestr(now,1)];
save(fullfile(path, filename), 'Answers');
close(Questionnaire);
pop_waiter(["Thank you so much!", ...
    "Que Dieu vous garde!"],1);
end


end





